#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CTMS")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CTMSConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DON1> DON1s
	{
		get
		{
			return this.GetTable<DON1>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON1")]
public partial class DON1
{
	
	private string _DON1_NUMBER;
	
	private string _DON1_LNAME;
	
	private string _DON1_FNAME;
	
	private string _DON1_MI;
	
	private System.Nullable<System.DateTime> _DON1_DOB;
	
	private string _DON1_SEX;
	
	private string _DON1_RACE;
	
	private System.Nullable<System.DateTime> _DON1_DOD;
	
	private string _DON1_COD;
	
	private string _DON1_TOD;
	
	private string _DON1_CONSENT;
	
	private string _DON1_C_RELATION;
	
	private string _DON1_C_LNAME;
	
	private string _DON1_C_FNAME;
	
	private string _DON1_C_MI;
	
	private string _DON1_C_ADDRESS;
	
	private string _DON1_C_ADDRESS2;
	
	private string _DON1_C_CITY;
	
	private string _DON1_C_STATE;
	
	private string _DON1_C_ZIP;
	
	private string _DON1_C_ZIP2;
	
	private string _DON1_C_PHONE;
	
	private string _DON1_HOSPITAL;
	
	private string _DON1_H_PHY;
	
	private string _DON1_REF_ORG;
	
	private string _DON1_REF_BY;
	
	private string _DON1_ATOP_ORDER;
	
	private string _DON1_COR_CASE;
	
	private string _DON1_FHOME;
	
	private string _DON1_TISS_NUM;
	
	private string _DON1_STATUS;
	
	private System.Nullable<System.DateTime> _DON1_DATE_ADDED;
	
	private string _DON1_TIME_ADDED;
	
	private System.Nullable<double> _DON1_WHO_ADDED;
	
	private System.Nullable<System.DateTime> _DON1_DATE_UPDATE;
	
	private System.Nullable<System.DateTime> _DON1_TIME_UPDATE;
	
	private System.Nullable<double> _DON1_WHO_UPDATE;
	
	private System.Nullable<System.DateTime> _DON1_DATE_DELETE;
	
	private System.Nullable<System.DateTime> _DON1_TIME_DELETE;
	
	private System.Nullable<double> _DON1_WHO_DELETE;
	
	private string _DON1_XREF;
	
	private string _DON1_REF_STAT;
	
	private string _DON1_COMMENT;
	
	private string _DON1_COMMENT2;
	
	private string _DON1_PROC_NUM;
	
	private string _DON1_BRANCH;
	
	private string _DON1_PROC_SITE;
	
	private string _DON1_BDN_KEY;
	
	private string _DON1_BPN_KEY;
	
	private string _DON1_DISB_RESTRICT;
	
	private System.Nullable<int> _DTYPE;
	
	public DON1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-NUMBER]", Storage="_DON1_NUMBER", DbType="VarChar(8)")]
	public string DON1_NUMBER
	{
		get
		{
			return this._DON1_NUMBER;
		}
		set
		{
			if ((this._DON1_NUMBER != value))
			{
				this._DON1_NUMBER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-LNAME]", Storage="_DON1_LNAME", DbType="VarChar(25)")]
	public string DON1_LNAME
	{
		get
		{
			return this._DON1_LNAME;
		}
		set
		{
			if ((this._DON1_LNAME != value))
			{
				this._DON1_LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-FNAME]", Storage="_DON1_FNAME", DbType="VarChar(15)")]
	public string DON1_FNAME
	{
		get
		{
			return this._DON1_FNAME;
		}
		set
		{
			if ((this._DON1_FNAME != value))
			{
				this._DON1_FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-MI]", Storage="_DON1_MI", DbType="VarChar(1)")]
	public string DON1_MI
	{
		get
		{
			return this._DON1_MI;
		}
		set
		{
			if ((this._DON1_MI != value))
			{
				this._DON1_MI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DOB]", Storage="_DON1_DOB", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_DOB
	{
		get
		{
			return this._DON1_DOB;
		}
		set
		{
			if ((this._DON1_DOB != value))
			{
				this._DON1_DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-SEX]", Storage="_DON1_SEX", DbType="VarChar(1)")]
	public string DON1_SEX
	{
		get
		{
			return this._DON1_SEX;
		}
		set
		{
			if ((this._DON1_SEX != value))
			{
				this._DON1_SEX = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-RACE]", Storage="_DON1_RACE", DbType="VarChar(2)")]
	public string DON1_RACE
	{
		get
		{
			return this._DON1_RACE;
		}
		set
		{
			if ((this._DON1_RACE != value))
			{
				this._DON1_RACE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DOD]", Storage="_DON1_DOD", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_DOD
	{
		get
		{
			return this._DON1_DOD;
		}
		set
		{
			if ((this._DON1_DOD != value))
			{
				this._DON1_DOD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-COD]", Storage="_DON1_COD", DbType="VarChar(2)")]
	public string DON1_COD
	{
		get
		{
			return this._DON1_COD;
		}
		set
		{
			if ((this._DON1_COD != value))
			{
				this._DON1_COD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-TOD]", Storage="_DON1_TOD", DbType="VarChar(15)")]
	public string DON1_TOD
	{
		get
		{
			return this._DON1_TOD;
		}
		set
		{
			if ((this._DON1_TOD != value))
			{
				this._DON1_TOD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-CONSENT]", Storage="_DON1_CONSENT", DbType="VarChar(1)")]
	public string DON1_CONSENT
	{
		get
		{
			return this._DON1_CONSENT;
		}
		set
		{
			if ((this._DON1_CONSENT != value))
			{
				this._DON1_CONSENT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-RELATION]", Storage="_DON1_C_RELATION", DbType="VarChar(2)")]
	public string DON1_C_RELATION
	{
		get
		{
			return this._DON1_C_RELATION;
		}
		set
		{
			if ((this._DON1_C_RELATION != value))
			{
				this._DON1_C_RELATION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-LNAME]", Storage="_DON1_C_LNAME", DbType="VarChar(25)")]
	public string DON1_C_LNAME
	{
		get
		{
			return this._DON1_C_LNAME;
		}
		set
		{
			if ((this._DON1_C_LNAME != value))
			{
				this._DON1_C_LNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-FNAME]", Storage="_DON1_C_FNAME", DbType="VarChar(15)")]
	public string DON1_C_FNAME
	{
		get
		{
			return this._DON1_C_FNAME;
		}
		set
		{
			if ((this._DON1_C_FNAME != value))
			{
				this._DON1_C_FNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-MI]", Storage="_DON1_C_MI", DbType="VarChar(1)")]
	public string DON1_C_MI
	{
		get
		{
			return this._DON1_C_MI;
		}
		set
		{
			if ((this._DON1_C_MI != value))
			{
				this._DON1_C_MI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-ADDRESS]", Storage="_DON1_C_ADDRESS", DbType="VarChar(30)")]
	public string DON1_C_ADDRESS
	{
		get
		{
			return this._DON1_C_ADDRESS;
		}
		set
		{
			if ((this._DON1_C_ADDRESS != value))
			{
				this._DON1_C_ADDRESS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-ADDRESS2]", Storage="_DON1_C_ADDRESS2", DbType="VarChar(30)")]
	public string DON1_C_ADDRESS2
	{
		get
		{
			return this._DON1_C_ADDRESS2;
		}
		set
		{
			if ((this._DON1_C_ADDRESS2 != value))
			{
				this._DON1_C_ADDRESS2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-CITY]", Storage="_DON1_C_CITY", DbType="VarChar(20)")]
	public string DON1_C_CITY
	{
		get
		{
			return this._DON1_C_CITY;
		}
		set
		{
			if ((this._DON1_C_CITY != value))
			{
				this._DON1_C_CITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-STATE]", Storage="_DON1_C_STATE", DbType="VarChar(2)")]
	public string DON1_C_STATE
	{
		get
		{
			return this._DON1_C_STATE;
		}
		set
		{
			if ((this._DON1_C_STATE != value))
			{
				this._DON1_C_STATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-ZIP]", Storage="_DON1_C_ZIP", DbType="VarChar(5)")]
	public string DON1_C_ZIP
	{
		get
		{
			return this._DON1_C_ZIP;
		}
		set
		{
			if ((this._DON1_C_ZIP != value))
			{
				this._DON1_C_ZIP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-ZIP2]", Storage="_DON1_C_ZIP2", DbType="VarChar(4)")]
	public string DON1_C_ZIP2
	{
		get
		{
			return this._DON1_C_ZIP2;
		}
		set
		{
			if ((this._DON1_C_ZIP2 != value))
			{
				this._DON1_C_ZIP2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-C-PHONE]", Storage="_DON1_C_PHONE", DbType="VarChar(14)")]
	public string DON1_C_PHONE
	{
		get
		{
			return this._DON1_C_PHONE;
		}
		set
		{
			if ((this._DON1_C_PHONE != value))
			{
				this._DON1_C_PHONE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-HOSPITAL]", Storage="_DON1_HOSPITAL", DbType="VarChar(4)")]
	public string DON1_HOSPITAL
	{
		get
		{
			return this._DON1_HOSPITAL;
		}
		set
		{
			if ((this._DON1_HOSPITAL != value))
			{
				this._DON1_HOSPITAL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-H-PHY]", Storage="_DON1_H_PHY", DbType="VarChar(4)")]
	public string DON1_H_PHY
	{
		get
		{
			return this._DON1_H_PHY;
		}
		set
		{
			if ((this._DON1_H_PHY != value))
			{
				this._DON1_H_PHY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-REF-ORG]", Storage="_DON1_REF_ORG", DbType="VarChar(2)")]
	public string DON1_REF_ORG
	{
		get
		{
			return this._DON1_REF_ORG;
		}
		set
		{
			if ((this._DON1_REF_ORG != value))
			{
				this._DON1_REF_ORG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-REF-BY]", Storage="_DON1_REF_BY", DbType="VarChar(40)")]
	public string DON1_REF_BY
	{
		get
		{
			return this._DON1_REF_BY;
		}
		set
		{
			if ((this._DON1_REF_BY != value))
			{
				this._DON1_REF_BY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-ATOP-ORDER]", Storage="_DON1_ATOP_ORDER", DbType="VarChar(1)")]
	public string DON1_ATOP_ORDER
	{
		get
		{
			return this._DON1_ATOP_ORDER;
		}
		set
		{
			if ((this._DON1_ATOP_ORDER != value))
			{
				this._DON1_ATOP_ORDER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-COR-CASE]", Storage="_DON1_COR_CASE", DbType="VarChar(1)")]
	public string DON1_COR_CASE
	{
		get
		{
			return this._DON1_COR_CASE;
		}
		set
		{
			if ((this._DON1_COR_CASE != value))
			{
				this._DON1_COR_CASE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-FHOME]", Storage="_DON1_FHOME", DbType="VarChar(4)")]
	public string DON1_FHOME
	{
		get
		{
			return this._DON1_FHOME;
		}
		set
		{
			if ((this._DON1_FHOME != value))
			{
				this._DON1_FHOME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-TISS-NUM]", Storage="_DON1_TISS_NUM", DbType="VarChar(3)")]
	public string DON1_TISS_NUM
	{
		get
		{
			return this._DON1_TISS_NUM;
		}
		set
		{
			if ((this._DON1_TISS_NUM != value))
			{
				this._DON1_TISS_NUM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-STATUS]", Storage="_DON1_STATUS", DbType="VarChar(1)")]
	public string DON1_STATUS
	{
		get
		{
			return this._DON1_STATUS;
		}
		set
		{
			if ((this._DON1_STATUS != value))
			{
				this._DON1_STATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DATE-ADDED]", Storage="_DON1_DATE_ADDED", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_DATE_ADDED
	{
		get
		{
			return this._DON1_DATE_ADDED;
		}
		set
		{
			if ((this._DON1_DATE_ADDED != value))
			{
				this._DON1_DATE_ADDED = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-TIME-ADDED]", Storage="_DON1_TIME_ADDED", DbType="VarChar(15)")]
	public string DON1_TIME_ADDED
	{
		get
		{
			return this._DON1_TIME_ADDED;
		}
		set
		{
			if ((this._DON1_TIME_ADDED != value))
			{
				this._DON1_TIME_ADDED = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-WHO-ADDED]", Storage="_DON1_WHO_ADDED", DbType="Float")]
	public System.Nullable<double> DON1_WHO_ADDED
	{
		get
		{
			return this._DON1_WHO_ADDED;
		}
		set
		{
			if ((this._DON1_WHO_ADDED != value))
			{
				this._DON1_WHO_ADDED = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DATE-UPDATE]", Storage="_DON1_DATE_UPDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_DATE_UPDATE
	{
		get
		{
			return this._DON1_DATE_UPDATE;
		}
		set
		{
			if ((this._DON1_DATE_UPDATE != value))
			{
				this._DON1_DATE_UPDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-TIME-UPDATE]", Storage="_DON1_TIME_UPDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_TIME_UPDATE
	{
		get
		{
			return this._DON1_TIME_UPDATE;
		}
		set
		{
			if ((this._DON1_TIME_UPDATE != value))
			{
				this._DON1_TIME_UPDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-WHO-UPDATE]", Storage="_DON1_WHO_UPDATE", DbType="Float")]
	public System.Nullable<double> DON1_WHO_UPDATE
	{
		get
		{
			return this._DON1_WHO_UPDATE;
		}
		set
		{
			if ((this._DON1_WHO_UPDATE != value))
			{
				this._DON1_WHO_UPDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DATE-DELETE]", Storage="_DON1_DATE_DELETE", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_DATE_DELETE
	{
		get
		{
			return this._DON1_DATE_DELETE;
		}
		set
		{
			if ((this._DON1_DATE_DELETE != value))
			{
				this._DON1_DATE_DELETE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-TIME-DELETE]", Storage="_DON1_TIME_DELETE", DbType="DateTime")]
	public System.Nullable<System.DateTime> DON1_TIME_DELETE
	{
		get
		{
			return this._DON1_TIME_DELETE;
		}
		set
		{
			if ((this._DON1_TIME_DELETE != value))
			{
				this._DON1_TIME_DELETE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-WHO-DELETE]", Storage="_DON1_WHO_DELETE", DbType="Float")]
	public System.Nullable<double> DON1_WHO_DELETE
	{
		get
		{
			return this._DON1_WHO_DELETE;
		}
		set
		{
			if ((this._DON1_WHO_DELETE != value))
			{
				this._DON1_WHO_DELETE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-XREF]", Storage="_DON1_XREF", DbType="VarChar(15)")]
	public string DON1_XREF
	{
		get
		{
			return this._DON1_XREF;
		}
		set
		{
			if ((this._DON1_XREF != value))
			{
				this._DON1_XREF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-REF-STAT]", Storage="_DON1_REF_STAT", DbType="VarChar(2)")]
	public string DON1_REF_STAT
	{
		get
		{
			return this._DON1_REF_STAT;
		}
		set
		{
			if ((this._DON1_REF_STAT != value))
			{
				this._DON1_REF_STAT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-COMMENT]", Storage="_DON1_COMMENT", DbType="VarChar(50)")]
	public string DON1_COMMENT
	{
		get
		{
			return this._DON1_COMMENT;
		}
		set
		{
			if ((this._DON1_COMMENT != value))
			{
				this._DON1_COMMENT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-COMMENT2]", Storage="_DON1_COMMENT2", DbType="VarChar(50)")]
	public string DON1_COMMENT2
	{
		get
		{
			return this._DON1_COMMENT2;
		}
		set
		{
			if ((this._DON1_COMMENT2 != value))
			{
				this._DON1_COMMENT2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-PROC-NUM]", Storage="_DON1_PROC_NUM", DbType="VarChar(9)")]
	public string DON1_PROC_NUM
	{
		get
		{
			return this._DON1_PROC_NUM;
		}
		set
		{
			if ((this._DON1_PROC_NUM != value))
			{
				this._DON1_PROC_NUM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-BRANCH]", Storage="_DON1_BRANCH", DbType="VarChar(3)")]
	public string DON1_BRANCH
	{
		get
		{
			return this._DON1_BRANCH;
		}
		set
		{
			if ((this._DON1_BRANCH != value))
			{
				this._DON1_BRANCH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-PROC-SITE]", Storage="_DON1_PROC_SITE", DbType="VarChar(3)")]
	public string DON1_PROC_SITE
	{
		get
		{
			return this._DON1_PROC_SITE;
		}
		set
		{
			if ((this._DON1_PROC_SITE != value))
			{
				this._DON1_PROC_SITE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-BDN-KEY]", Storage="_DON1_BDN_KEY", DbType="VarChar(9)")]
	public string DON1_BDN_KEY
	{
		get
		{
			return this._DON1_BDN_KEY;
		}
		set
		{
			if ((this._DON1_BDN_KEY != value))
			{
				this._DON1_BDN_KEY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-BPN-KEY]", Storage="_DON1_BPN_KEY", DbType="VarChar(12)")]
	public string DON1_BPN_KEY
	{
		get
		{
			return this._DON1_BPN_KEY;
		}
		set
		{
			if ((this._DON1_BPN_KEY != value))
			{
				this._DON1_BPN_KEY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DON1-DISB-RESTRICT]", Storage="_DON1_DISB_RESTRICT", DbType="VarChar(1)")]
	public string DON1_DISB_RESTRICT
	{
		get
		{
			return this._DON1_DISB_RESTRICT;
		}
		set
		{
			if ((this._DON1_DISB_RESTRICT != value))
			{
				this._DON1_DISB_RESTRICT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTYPE", DbType="Int")]
	public System.Nullable<int> DTYPE
	{
		get
		{
			return this._DTYPE;
		}
		set
		{
			if ((this._DTYPE != value))
			{
				this._DTYPE = value;
			}
		}
	}
}
#pragma warning restore 1591
